name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build app
      run: |
        npm install
        npm run build

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build -t lymims/learn-lymim-com .
    - name: Login to Registry
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}
    - name: Push Image
      run: |
        docker push lymims/learn-lymim-com
